// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHxlVXwyWf60x-ASgl_pz9xfKS3hdVpKY',
    appId: '1:61174269322:android:75dc3eace7ac5ad9e6b473',
    messagingSenderId: '61174269322',
    projectId: 'juventud-dorjadash',
    storageBucket: 'juventud-dorjadash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMf4P2gePQN667FQF0v27lOmNiIvAMRUA',
    appId: '1:61174269322:ios:599b4763973c4c22e6b473',
    messagingSenderId: '61174269322',
    projectId: 'juventud-dorjadash',
    storageBucket: 'juventud-dorjadash.appspot.com',
    iosClientId: '61174269322-2ke1t5ksi7o8kkfi5s6c7c7rmed9esg4.apps.googleusercontent.com',
    iosBundleId: 'com.aupikholtz.dorjapp',
  );
}
